### ISSUE TITLE
Doesn't seem to send emails?

### ISSUE THREAD

**Issue by Colbywolf** [p0ody/ff2ebook-node#1]
Howdy!

Love this thing :) However, the node version does not seem to send emails?

I tried it a week or so ago, and again today with the same issue, while the 'modern' (aka, not new, not old)  version seems to be issue free. :) 

Not sure if this is a "known issue" or what, but I figure I'm here and testing your fantastic tool, so.... :)

**Comment by p0ody** [comment]
This should now be working as intended, Google(Gmail) from my site account was blocking connecting from my webhost
